# Generated by Django 2.1.2 on 2019-03-28 09:03

from django.db import migrations, models
import django.db.models.deletion
import gb_merchant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gb_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '门店分类',
                'verbose_name_plural': '门店分类',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='最多150位', max_length=150, verbose_name='评论内容')),
                ('shopid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gb_account.Merchants', verbose_name='门店id')),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gb_account.Users', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cImg', models.ImageField(help_text='广告图片', upload_to='commercial/', verbose_name='广告图片')),
                ('trackid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gb_account.Merchants', verbose_name='门店id')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
            },
        ),
        migrations.CreateModel(
            name='MerchantClass',
            fields=[
                ('classid', models.CharField(help_text='最多4位', max_length=4, primary_key=True, serialize=False, verbose_name='分类id')),
                ('classtype', models.CharField(help_text='分类类型', max_length=2, verbose_name='分类类型')),
                ('className', models.CharField(help_text='最多10位', max_length=10, unique=True, verbose_name='分类名')),
            ],
            options={
                'verbose_name': '门店类型分类名',
                'verbose_name_plural': '门店类型分类名',
            },
        ),
        migrations.CreateModel(
            name='MerchantImgSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgAddress', models.ImageField(help_text='图片地址', upload_to=gb_merchant.models.MerchantImgSet.mer_imgset_path, verbose_name='图片地址')),
                ('shopid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gb_account.Merchants', verbose_name='门店编号')),
            ],
            options={
                'verbose_name': '门店图片集',
                'verbose_name_plural': '门店图片集',
            },
        ),
        migrations.CreateModel(
            name='ServiceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sclassName', models.CharField(help_text='最多20位', max_length=20, verbose_name='服务分类名')),
                ('isDelete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('shopid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gb_account.Merchants', verbose_name='门店编号')),
            ],
            options={
                'verbose_name': '门店服务分类名',
                'verbose_name_plural': '门店服务分类名',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(help_text='最大20位', max_length=20, verbose_name='服务名')),
                ('sPrice', models.DecimalField(decimal_places=2, help_text='0.00-99999.99元', max_digits=7, verbose_name='价格')),
                ('sImg', models.ImageField(help_text='服务图片', upload_to=gb_merchant.models.Services.ser_img_path, verbose_name='服务图片')),
                ('sDesc', models.TextField(help_text='最大50位', max_length=50, verbose_name='服务描述')),
                ('isNeedFile', models.BooleanField(default=False, verbose_name='是否需要上传文件')),
                ('isOnlinePay', models.BooleanField(default=False, verbose_name='是否在线支付')),
                ('isDelete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('sclassid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gb_merchant.ServiceClass', verbose_name='服务分类编号')),
                ('shopid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gb_account.Merchants', verbose_name='门店编号')),
            ],
            options={
                'verbose_name': '门店服务操作信息',
                'verbose_name_plural': '门店服务操作信息',
            },
        ),
        migrations.AddField(
            model_name='classitem',
            name='classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gb_merchant.MerchantClass', verbose_name='分类id'),
        ),
        migrations.AddField(
            model_name='classitem',
            name='shopid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gb_account.Merchants', verbose_name='门店id'),
        ),
    ]
