# Generated by Django 2.1.2 on 2019-03-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gb_merchant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantclass',
            name='classtype',
        ),
    ]
